version: '3.9'
services:
  db:
    image: postgres:16
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: casapp
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  backend:
    build:
      context: ./backend
    restart: unless-stopped
    environment:
      DATABASE_URL: postgresql://postgres:postgres@db:5432/casapp
      DJANGO_SECRET_KEY: changeme
      DJANGO_DEBUG: 'false'
      DJANGO_ALLOWED_HOSTS: '*'
      DJANGO_USE_FORCE_SCRIPT_NAME: 'true'
      DJANGO_FORCE_SCRIPT_NAME: /casapp
    depends_on:
      - db
    ports:
      - "8003:8003"

  frontend:
    build:
      context: ./frontend
    restart: unless-stopped
    environment:
      NEXT_PUBLIC_API_BASE: /casapp/api
    depends_on:
      - backend
    ports:
      - "3000:3000"

volumes:
  db_data:
