version: "3.9"
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    image: casapp-web:latest
    ports:
      - "3000:3000"
    environment:
      # Persist SQLite database under /data, and point Prisma to it
      DATABASE_URL: file:/data/dev.db
      NODE_ENV: production
      # Set NextAuth or other env here if used
      # NEXTAUTH_URL: http://localhost:3000
    volumes:
      # Persist Prisma SQLite DB
      - db-data:/data
      # Persist uploads, served via /public/uploads symlink created by entrypoint
      - uploads-data:/uploads
    restart: unless-stopped

volumes:
  db-data: {}
  uploads-data: {}
